### ISSUE TITLE
This crate is very unsound

### ISSUE THREAD

**Issue by RalfJung** [valarauca/inconceivable#1]
The `inconceivable!` macro can be used from safe code, which makes this crate unsound -- a fatal bug for any crate.

The concept of having an 'unreachable' macro with a debug assertion makes a lot of sense, but the macro absolutely needs to be unsafe to call.

Indeed, as the crate description says
> This crate is created purely to inject undefined behavior into stable, safe rust.

This is the antithesis of Rust. (It makes me wonder whether this is even serious or just trying to prove some kind of point.)

**Comment by valarauca** [comment]
> The inconceivable! macro can be used from safe code, which makes this crate unsound -- a fatal bug for any crate.

So can `unsafe` blocks. 

> The concept of having an 'unreachable' macro with a debug assertion makes a lot of sense

[Using `unreachable!` has some trade-offs, see last paragraph of this section](https://doc.rust-lang.org/std/hint/fn.unreachable_unchecked.html#safety)

> It makes me wonder whether this is even serious or just trying to prove some kind of point

[IDK there are some well documented use cases](https://doc.rust-lang.org/std/hint/fn.unreachable_unchecked.html#examples)

> This is the antithesis of Rust

![](https://i.kym-cdn.com/entries/icons/original/000/000/346/COOLSTORY.jpg)

Short of trolling, why would you open an issue to say this? 

Could you have said it in a more constructive manner?

**Comment by valarauca** [comment]
> It makes me wonder whether this is even serious or just trying to prove some kind of point

Oh no, it is serious. [Please review the doc comment](https://github.com/valarauca/inconceivable/blob/4bfa21f7f37cc62d495af70465ab205c80405ed9/src/lib.rs#L33-#L36).

The goal is to permit the LLVM to be able to more aggressively prune branches that are not provable at compile time, but impossible due to program structure. Philosophical objections aside concerning safety & purity aside this is useful and greatly impacts micro-benchmarks.

The general assumption that [predictable branches are free](https://stackoverflow.com/questions/30904380/are-correct-branch-predictions-free) is in fact [very untrue (intel errata link)](https://www.intel.com/content/dam/support/us/en/documents/processors/mitigations-jump-conditional-code-erratum.pdf). By carefully doing pref analysis of a sample of code you can note that front end stalls are occurring for maligned branches and their state is not being cached. While the LLVM has shipped some features to address [(link)](https://reviews.llvm.org/D70157) this feature is not consistently enabled and passing arguments to the LLVM through cargo -> rustc -> llvm is extremely difficult/annoying. [Rustc even has an open issue about this](https://github.com/rust-lang/rust/issues/26338).

This is a long way of saying that pruning unnecessary branches is useful.

While you undoubtedly have objections to this crate, it does serve a useful purpose. Until static analysis significantly improves being able to configure a build where I can in no uncertain terms tell the compiler "_simply treat all these conditions as impossible_" is extremely useful.

---

All this said the crate is only UB if whatever is importing this crate enables it via `cfg` options.

The crate is safe by default as outlined [in the readme](https://github.com/valarauca/inconceivable#developer-controllable-options). Unsafe behavior is only available if somebody opts-into it.
